import javax.swing.ImageIcon;

public class StaffDetails extends javax.swing.JPanel {
    
    public StaffDetails(Database.Staff result) {
        initComponents();
        // Fill out every field with the proper data
        nameBox.setText(result.name);
        depBox.setText(result.department);
        emailBox.setText(result.email);
        phoneBox.setText(result.phone);
        officeBox.setText(result.officeLoc);
        hoursBox.setText(result.officeHour);
        researchBox.setText(result.research);
        coursesBox.setText(result.courses);
        imageIcon.setIcon(new ImageIcon(result.icon.getScaledInstance(105, 140, 0)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageIcon = new javax.swing.JLabel();
        hoursLabel = new javax.swing.JLabel();
        researchLabel = new javax.swing.JLabel();
        researchBox = new javax.swing.JTextArea();
        coursesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursesBox = new javax.swing.JTextArea();
        emailBox = new javax.swing.JTextArea();
        phoneBox = new javax.swing.JTextArea();
        officeBox = new javax.swing.JTextArea();
        hoursBox = new javax.swing.JTextArea();
        depBox = new javax.swing.JTextArea();
        nameBox = new javax.swing.JTextArea();

        hoursLabel.setText("Office Hours:");

        researchLabel.setText("Research:");

        researchBox.setEditable(false);
        researchBox.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        researchBox.setLineWrap(true);
        researchBox.setMinimumSize(new java.awt.Dimension(16, 16));
        researchBox.setOpaque(false);

        coursesLabel.setText("Courses:");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.controlShadow));
        jScrollPane1.setOpaque(false);

        coursesBox.setEditable(false);
        coursesBox.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        coursesBox.setLineWrap(true);
        coursesBox.setMinimumSize(new java.awt.Dimension(18, 18));
        coursesBox.setOpaque(false);
        jScrollPane1.setViewportView(coursesBox);

        emailBox.setEditable(false);
        emailBox.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        emailBox.setLineWrap(true);
        emailBox.setMinimumSize(new java.awt.Dimension(16, 16));
        emailBox.setOpaque(false);

        phoneBox.setEditable(false);
        phoneBox.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        phoneBox.setLineWrap(true);
        phoneBox.setMinimumSize(new java.awt.Dimension(16, 16));
        phoneBox.setOpaque(false);

        officeBox.setEditable(false);
        officeBox.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        officeBox.setLineWrap(true);
        officeBox.setMinimumSize(new java.awt.Dimension(16, 16));
        officeBox.setOpaque(false);

        hoursBox.setEditable(false);
        hoursBox.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        hoursBox.setLineWrap(true);
        hoursBox.setMinimumSize(new java.awt.Dimension(16, 16));
        hoursBox.setOpaque(false);

        depBox.setEditable(false);
        depBox.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        depBox.setLineWrap(true);
        depBox.setMinimumSize(new java.awt.Dimension(16, 16));
        depBox.setOpaque(false);

        nameBox.setEditable(false);
        nameBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameBox.setLineWrap(true);
        nameBox.setMinimumSize(new java.awt.Dimension(16, 16));
        nameBox.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hoursLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hoursBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(emailBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(officeBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(depBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(coursesLabel)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(researchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(researchBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(officeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hoursLabel)
                            .addComponent(hoursBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(researchLabel)
                    .addComponent(researchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coursesLabel)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea coursesBox;
    private javax.swing.JLabel coursesLabel;
    private javax.swing.JTextArea depBox;
    private javax.swing.JTextArea emailBox;
    private javax.swing.JTextArea hoursBox;
    private javax.swing.JLabel hoursLabel;
    private javax.swing.JLabel imageIcon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea nameBox;
    private javax.swing.JTextArea officeBox;
    private javax.swing.JTextArea phoneBox;
    private javax.swing.JTextArea researchBox;
    private javax.swing.JLabel researchLabel;
    // End of variables declaration//GEN-END:variables
}
